# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the pylint-orb
  pylint: qventus/python-lint@volatile
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "pylint"
  pylint:
    # Run the welcome/run job in its own container
    jobs:
      - pylint/lint