# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the pylint-orb
  python: circleci/python@0.2.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "pylint"
  pylint:
    # Run the pylint job
    jobs:
      build:
        executor: python/default
        steps:
          - checkout
          - python/load-cache
          - python/install-deps
          - python/save-cache
          - run:
              command: |
                # pytest would be a dep in requirements.txt
                pytest
              name: Test
    orbs:
      python: circleci/python@0.1
    version: 2.1
    workflows:
      main:
        jobs:
          - build
