version: 2

jobs:

  Run-With-Python:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout # get code from git
      - run:
          name: Running In A Container With Python
          command: |
            python3 *.py

  Deploy-To-Remote:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo jee"

  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - Run-With-Python
      - Hold-For-Approval:
          type: approval
          requires:
            - Run-With-Python
      - Deploy-To-Remote:
          requires:
            - Hold-For-Approval
          filters:
            branches:
              only: test # only deploy on the test branch
      - Now-Complete:
          requires:
            - Deploy-To-Remote